### ISSUE TITLE
>100% Wife scores with some charts

### ISSUE THREAD

**Issue by Chiyozel** [xwidghet/stepmania#15]
I had some weird thing going on with one chart in particular that isn't too hard, I just wanted to test it and I've had a score **over 100% (111.15)** on Wife system. I am not sure if this has to do with lifts, since they are one of the main things in the chart. It also has fakes (3 by the end) but they shouldn't have a huge influence towards final percentage.

![111.15% Wife?](https://cdn.discordapp.com/attachments/123159501414072322/267377796454547486/StepMania_2017-01-06_17-00-57.png)

[Chart download for testing.](http://chiyozel.com/FUCK/michelbaie%20tvsize%20pad.zip)

**Comment by MinaciousGrace** [comment]
just eyeballing it my guess is you're right about lifts, they're probably getting scored by the tap note function and not the hold note function and producing extra points, although given how many lifts there are you would expect the percent to be even higher

i'll look into it tonight or tomorrow and let you know when i've figured it out, thanks for the heads up

**Comment by MinaciousGrace** [comment]
ok it was a simple oversight in lift notes not being added to the total available number of points in the file
