### ISSUE TITLE
Issues with songs longer than approx 70 mins

### ISSUE THREAD

**Issue by GruzzlyBear** [xwidghet/stepmania#2]
Hello,

I recently tried playing the song "1hr54min JS challenge" in your build of StepMania and the game crashed as soon as it received input. This also occurred with two other files - YONDERDOME (Overloading Stamina Training Megapack EX) and Pure Trance Anthems (ultramarathon gigapack) - both of which are longer than 70 mins long. I also tried the Hatsune Miku 10000 digits of pi file (ultramarathon gigapack), and that worked (the file is 68 minutes long).

Other side effects of this problem (Til Death theme):
- File md5 or hex or whatever is "Invalid" (note this also happens with some extremely short files such as TOASTY and You Suffer)
- In the case of the file Pure Trance Anthems, the General tab breaks (nothing shows up-percentage, score etc.)

Changing the theme to something different did not fix the problem either, so the problem is related to the build somehow.

Hopefully this info helps!

Pastebin of crash log: http://pastebin.com/JsSTs5T2

~gruz

**Comment by xwidghet** [comment]
Thank you for your report, will be fixed in next release.

**Comment by MinaciousGrace** [comment]
fixed
