### ISSUE TITLE
Move Music Select Filter system out of gamestate (to a FILTERMAN I guess?)

### ISSUE THREAD

**Issue by MinaciousGrace** [xwidghet/stepmania#31]
Filter settings should persist between gameplay screens so they can't exist within the musicwheel object, gamestate is getting bloasted and I've even run into issues with adding more variables into it causing instant crashes upon game load

**Comment by dadcop2** [comment]
almost done with this, just need to make sure i wont have any issues merging

**Comment by MinaciousGrace** [comment]
this was done a while ago oops
