### ISSUE TITLE
Etterna crashes after setting rate mod below 0.7x - above 2.0x

### ISSUE THREAD

**Issue by FiskSM** [xwidghet/stepmania#43]
it's supposed to be fixed since 0.54a but it keeps happening :'c

**Comment by MinaciousGrace** [comment]
yeah one of the crashes was fixed and another went unnoticed, though, 2.05x shouldn't crash as a result of the fix that was made

it'll be fixed by the end of today

**Comment by FiskSM** [comment]
thank you! <3
