### ISSUE TITLE
How to use on Mac?

### ISSUE THREAD

**Issue by jacc** [xwidghet/stepmania#5]
Got the link from a friend, been wanting to try. After downloading and unzip, I can't find a .app. Do I have to compile in Xcode?

**Comment by xwidghet** [comment]
We have not added support for mac for the difficulty calculator yet, which will make mac builds fail. Once support has been added building should work after running through cmake, which there's directions for in the Build directory.

**Comment by jacc** [comment]
Any ETA on when the difficulty calculator and a full .app will be released?

**Comment by MinaciousGrace** [comment]
don't expect it before the new year

**Comment by jacc** [comment]
gg bois
