### ISSUE TITLE
fix for Lua-specified sound files on ScreenSelectMusic

### ISSUE THREAD

**Issue by RhythmLunatic** [xwidghet/stepmania#54]
Basically this bug seems to have never been fixed in 5.0.X, can you add it to Etterna?

https://github.com/stepmania/stepmania/issues/1347

**Comment by MinaciousGrace** [comment]
ok I looked over this quickly, it should be straightforward to implement the actual fix part of the commit, however I'm traveling and haven't had the chance to set up anything dev related so it'll have to wait until I get that chance unless one of the other devs wants to do it before then

I suppose I could just make the fix blind and pr it to make sure it compiles, but that sort of seems irresponsible

**Comment by RhythmLunatic** [comment]
I added the fix myself, but it causes another bug where if you scroll over a song and then switch back to the folder quickly it will stop playing the folder music.

Additionally if the song doesn't have a preview file (BMSes usually don't) it will stay muted until you scroll over a song that does have one and then back.

**Comment by nico-abram** [comment]
Does that also happen on vanilla?

**Comment by RhythmLunatic** [comment]
If you mean regular StepMania, yes. The master branch has the muted preview bug, or something like it. https://github.com/stepmania/stepmania/issues/1561
